apiVersion: batch/v1
kind: Job
metadata:
  name: client-auth-role-setup
  namespace: client
spec:
  template:
    spec:
      containers:
      - name: client-auth-setup
        image: client-auth-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "setup"
        - name: APP_SETUP_ROLES
          valueFrom:
            configMapKeyRef:
              name: client-auth-config
              key: roles
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://host.docker.internal:10001/auth_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
      restartPolicy: OnFailure
  backoffLimit: 3
