# ConfigMap for database configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-config
  namespace: coursy
data:
  POSTGRES_DB: auth_db
  POSTGRES_USER: postgres
---
# Secret for database password
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: coursy
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded "postgres"