# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: users-db-service
  namespace: coursy
spec:
  selector:
    app: users-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP