# Users Application Service
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: coursy
spec:
  selector:
    app: users-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP