apiVersion: v1
kind: ConfigMap
metadata:
  name: videos-app-config
  namespace: coursy
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://videos-db-service:5432/videos_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  # MinIO Configuration
  MINIO_ENDPOINT: http://minio-service:9000
  MINIO_BUCKET_NAME: coursy-videos
---
# videos/videos-app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: videos-app-secret
  namespace: coursy
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM= # base64 encoded "postgres"
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg== # base64 encoded "minioadmin"
  MINIO_SECRET_KEY: bWluaW9hZG1pbg== # base64 encoded "minioadmin"