# PersistentVolumeClaim for PostgreSQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: courses-db-pvc
  namespace: coursy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi