# Courses Application Service
apiVersion: v1
kind: Service
metadata:
  name: courses-service
  namespace: coursy
spec:
  selector:
    app: courses-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP